### ISSUE TITLE
OSError: [Errno 2] No such file or directory on Mac ElCapitan

### ISSUE THREAD

**Issue by janmasarik** [YPlan/treepoem#25]
Hi, got this when trying to call generate_barcode...

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/treepoem/__init__.py", line 123, in generate_barcode
    bbox_lines = _get_bbox(code)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/treepoem/__init__.py", line 84, in _get_bbox
    stderr=subprocess.PIPE,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by adamchainz** [comment]
This is probably because you don't have Ghostscript installed: https://github.com/YPlan/treepoem/blob/master/treepoem/__init__.py#L79

Sorry the README doesn't document any install process

**Comment by adamchainz** [comment]
N.B. on mac it's `brew install ghostscript`

**Comment by adamchainz** [comment]
Documenting in #26

**Comment by janmasarik** [comment]
thanks 👍
