### ISSUE TITLE
How to install in windows?

### ISSUE THREAD

**Issue by Niedzwiedzw** [YPlan/treepoem#43]
^

**Comment by adamchainz** [comment]
As long as you can install ghostscript so it's callable with `gs`, you should be able to install from `pip`. If you find an easy way of installing it please feel free to add to the documentation. Sorry the code isn't tested on Windows.

**Comment by Niedzwiedzw** [comment]
Adding gs.bat containing 
`Start "" "C:\Program Files (x86)\gs\gs9.20\bin\gswin32c.exe" %*` to PATH didnt help, even thoigh typing gs in cmd runs it. Here is the error:
`Traceback (most recent call last):
  File "C:/Users/Niedzwiedz/PycharmProjects/barcodeScanner/main.py", line 8, in <module>
    options={},
  File "C:\Users\Niedzwiedz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\treepoem\__init__.py", line 123, in generate_barcode
    bbox_lines = _get_bbox(code)
  File "C:\Users\Niedzwiedz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\treepoem\__init__.py", line 84, in _get_bbox
    stderr=subprocess.PIPE,
  File "C:\Users\Niedzwiedz\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Niedzwiedz\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku`


Code executed:
`import treepoem



image = treepoem.generate_barcode(
                                barcode_type='qrcode',  # One of the BWIPP supported codes.
                                data='barcode payload',
                                options={},
                                )

`image.save('barcode.png')  # This is an instance of `PIL.EpsImagePlugin.EpsImageFile`

Maybe you see something here...

**Comment by adamchainz** [comment]
Afraid I don't know enough about windows and paths to debug that. Potentially it has to be called 'gs' instead of 'gs.bat', but I'm just guessing.
